# Generated by Django 4.0.2 on 2022-04-05 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name of the user', max_length=30)),
                ('last_name', models.CharField(help_text='Last name of the user', max_length=30)),
                ('email', models.EmailField(help_text='User email', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the post created by the user', max_length=100)),
                ('content', models.CharField(help_text='The content of the post created by the user', max_length=1000)),
                ('date_posted', models.DateField(verbose_name='Date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Comment made in response to another post', max_length=500)),
                ('date_posted', models.DateField(verbose_name='Date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.user')),
                ('post_commented_on', models.ForeignKey(help_text='The post this comment was in response to', on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
        ),
    ]
